root: true

parserOptions:
  ecmaVersion: latest

extends:
  - airbnb-base
  - plugin:jest/recommended

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  import/extensions: 0
  indent:
    - error
    - 2
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - req
        - reply
        - acc
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allow:
        - _t
        - __dirname
        - __filename
